version: "3.8"

services:
  movie-fes:
    image: ygutara/movie-fes:latest
    container_name: movie-fes
    restart: always
    build:
      context: "./"
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgresnew
      DB_PORT: 5432
      DB_USER: postgresql
      DB_PASSWORD: postgresql
      DB_NAME: movie_festival
      APP_PORT: 8080
    networks:
      - network_example
    depends_on:
      - postgresnew

  postgresnew:
    image: postgres:alpine3.17
    container_name: postgresnew
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: movie_festival
    networks:
      - network_example
    ports:
      - "5432:5432"

networks:
  network_example:
    name: network_example
    driver: bridge